spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev

#server:
#  port: 0

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-pass-word-vai1@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${sping.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

logging:
  file:
    name: ./logs/log-file.log

# ANTIGO
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

# NOVO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

resilience4j:
  circuitbreaker:
    instances:
      clientes:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      clientes:
        max-attempts: 3
        wait-duration: 1s
