spring:
  application:
    name: msclientes
  datasource:
    url: jdbc:postgresql://postgres:5432/avaliador_credito
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: msclientes
    default-schema: msclientes
  jpa:
    properties:
      hibernate.default_schema: msclientes

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-pass-word-vai1@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: ./logs/log-file.log

# ANTIGO
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

# NOVO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

resilience4j:
  circuitbreaker:
    instances:
      clientes:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      clientes:
        max-attempts: 3
        wait-duration: 1s