spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avaliador_credito
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate.default_schema: mscartoes
  flyway:
    enabled: true
    schemas: mscartoes
    default-schema: mscartoes
